# Generated by Django 4.1.6 on 2023-03-04 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0010_alter_subjectmodel_section_code'),
        ('room', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=20)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roommodel')),
                ('subject_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subjectmodel')),
            ],
        ),
    ]
