# Generated by Django 4.1.6 on 2023-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='days',
            field=models.CharField(max_length=100),
        ),
    ]
