# Generated by Django 4.1.6 on 2023-03-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exammodel_course_code_exammodel_section_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='instructor_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='section_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='exammodel',
            name='subject_code',
            field=models.CharField(max_length=10),
        ),
    ]
