# Generated by Django 4.1.6 on 2023-02-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginuser', '0003_loginuser_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='status',
            field=models.CharField(choices=[('irregular', 'Irregular'), ('regular', 'Regular')], default='Select Status', max_length=20),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='usertype',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='Select User Type', max_length=20),
        ),
    ]
