# Generated by Django 4.1.6 on 2023-02-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='days',
            new_name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='room',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default='Select Status', max_length=20),
        ),
    ]
