# Generated by Django 4.1.6 on 2023-03-18 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_instructor_id_studentmodel_section_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='subject_code',
        ),
    ]
