# Generated by Django 4.1.6 on 2023-03-18 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_studentschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentSchedule',
            new_name='StudentScheduleModel',
        ),
    ]
