# Generated by Django 4.1.6 on 2023-02-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('program_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_year', models.CharField(max_length=20)),
                ('period', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('program_code', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('lecture', models.IntegerField()),
                ('lab', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumYearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_year', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
