# Generated by Django 4.1.6 on 2023-02-22 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculummodel',
            name='course_name',
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.coursemodel'),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='curriculum_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.curriculumyearmodel'),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='program_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.academicprogrammodel'),
        ),
    ]
