# Generated by Django 4.1.6 on 2023-02-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_coursemodel_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculummodel',
            name='period',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester')], max_length=20),
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='program_code',
            field=models.CharField(max_length=20),
        ),
    ]
