# Generated by Django 4.1.6 on 2023-02-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_curriculummodel_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=20, unique=True)),
                ('subject_description', models.CharField(max_length=100)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.coursemodel')),
                ('program_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.academicprogrammodel')),
            ],
        ),
    ]
