# Generated by Django 4.1.6 on 2023-02-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_curriculummodel_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='curriculummodel',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.subjectmodel'),
        ),
        migrations.AddField(
            model_name='subjectmodel',
            name='section_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='curriculum.sectionmodel'),
        ),
    ]
