# Generated by Django 4.1.6 on 2023-02-27 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_sectionmodel_alter_curriculummodel_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='section_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.sectionmodel'),
        ),
    ]
