# Generated by Django 4.1.6 on 2023-03-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_curriculummodel_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectmodel',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
