# Generated by Django 4.1.6 on 2023-03-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_subjectmodel_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='section_code',
        ),
    ]
