# Generated by Django 4.1.6 on 2023-03-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_remove_subjectmodel_section_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectmodel',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='subjectmodel',
            name='program_code',
        ),
        migrations.AlterField(
            model_name='subjectmodel',
            name='subject_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
