# Generated by Django 4.1.6 on 2023-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_instructormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormodel',
            name='time_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='time_out',
            field=models.TimeField(null=True),
        ),
    ]
