# Generated by Django 4.1.6 on 2023-05-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_alter_instructormodel_time_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='time_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='time_out',
            field=models.IntegerField(null=True),
        ),
    ]
