# Generated by Django 4.1.6 on 2023-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_instructormodel_days_alter_instructormodel_time_in_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorModel',
        ),
    ]
