# Generated by Django 4.1.6 on 2023-05-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_delete_instructormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=15)),
                ('days', models.IntegerField(null=True)),
                ('time_in', models.IntegerField(null=True)),
                ('time_out', models.IntegerField(null=True)),
                ('academic_year', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('subject_code', models.CharField(max_length=50)),
                ('units', models.IntegerField()),
                ('room', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
            ],
        ),
    ]
