# Generated by Django 4.1.6 on 2023-05-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0023_instructormodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructormodel',
            name='days',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
