# Generated by Django 4.1.6 on 2023-05-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_alter_instructormodel_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorModel',
        ),
    ]
