# Generated by Django 4.1.6 on 2023-05-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_instructormodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesor', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=50, null=True)),
                ('start', models.IntegerField(null=True)),
                ('end', models.IntegerField(null=True)),
                ('subject_code', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=20)),
                ('semester', models.IntegerField()),
                ('units', models.IntegerField()),
            ],
        ),
    ]
