# Generated by Django 4.1.6 on 2023-02-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(max_length=20)),
                ('level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='Select Level', max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('program_code', models.CharField(max_length=20)),
                ('subject_code', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=20)),
                ('days', models.CharField(max_length=20)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
            ],
        ),
    ]
