# Generated by Django 4.1.6 on 2023-02-21 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_facultymodel_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.roommodel'),
        ),
    ]
