# Generated by Django 4.1.6 on 2023-02-22 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_initial'),
        ('pages', '0003_roommodel_alter_facultymodel_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.roommodel'),
        ),
        migrations.DeleteModel(
            name='RoomModel',
        ),
    ]
