# Generated by Django 4.1.6 on 2023-02-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_facultymodel_room_delete_roommodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultymodel',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='program_code',
        ),
    ]
