# Generated by Django 4.1.6 on 2023-03-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_facultymodel_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='days',
            field=models.CharField(max_length=100),
        ),
    ]
