# Generated by Django 4.1.6 on 2023-03-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_facultymodel_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='section_code',
            field=models.CharField(default='', max_length=20),
        ),
    ]
