# Generated by Django 4.1.6 on 2023-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_facultymodel_section_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='section_code',
            field=models.CharField(max_length=20),
        ),
    ]
