# Generated by Django 4.1.6 on 2023-03-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_facultymodel_course_code_facultymodel_program_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='course_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='program_code',
            field=models.CharField(max_length=20),
        ),
    ]
