# Generated by Django 4.1.6 on 2023-03-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_facultymodel_course_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymodel',
            name='room',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='subject_code',
            field=models.CharField(max_length=20),
        ),
    ]
