# Generated by Django 4.1.6 on 2023-02-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomModel',
        ),
    ]
